### ISSUE TITLE
Module fails to import into Azure Automation Assets

### ISSUE THREAD

**Issue by jahmai-ca** [azurefieldnotes/Avanade.AzureAD#1]
If you go into an Azure Automation account and attempt to import this module into the assets from the gallery, it fails to import due to missing property DefaultParameterSetName on ParameterAttribute.

Looking at the module source, it appears to mix DefaultParameterSetName and ParameterSetName on different Parameter definitions.

The way to fix this seems to be to change them all to use ParameterSetName instead.

**Comment by cspeers** [comment]
This was resolved in last commit.
